name: animeshin

version: 1.0.1

description: Unofficial multi-platform AniList application integrated with AniLiberty.

repository: https://github.com/emp0ry/animeshin

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management.
  flutter_riverpod: ^2.6.1

  # Routing.
  go_router: ^16.0.0

  # Data fetching.
  http: ^1.4.0

  # OAuth PKCE (SHA-256)
  crypto: ^3.0.6

  # Lightweight storage.
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Access to device storage. Used for [hive] setup.
  path_provider: ^2.1.5

  # Secure storage for the access tokens.
  flutter_secure_storage: ^9.2.4

  # Markdown to HTML parsing.
  markdown: ^7.3.0

  # Used for configuring [cached_network_image].
  flutter_cache_manager: ^3.4.1

  # Image caching.
  cached_network_image: ^3.4.1

  # Opening links in the browser.
  url_launcher: ^6.3.0
  flutter_js: ^0.8.5

  # Access to platform theme and easy theme interpolation.
  dynamic_color: ^1.7.0

  # Background tasks for notification fetching.
  workmanager: ^0.9.0

  # Sending device notifications.
  flutter_local_notifications: ^19.4.0

  # Parsing html into flutter widgets.
  flutter_widget_from_html_core: ^0.17.0

  # An addition to the material icons.
  ionicons: ^0.2.2

  flutter_slidable: ^4.0.0
  window_manager: ^0.5.1
  timezone: ^0.10.1
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3

  # video_player: ^2.10.0
  # video_player_android: ^2.8.11
  # video_player_avfoundation: ^2.8.3
  # video_player_web: ^2.4.0
  # video_player_win: ^3.2.0
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_video: ^1.0.6
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_android_video: ^1.3.7
  media_kit_libs_ios_video: ^1.1.4

  html: ^0.15.6

  # For Export
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  share_plus: ^11.1.0
  intl: ^0.20.2
  xml: ^6.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0a0011"
  adaptive_icon_foreground: "assets/icons/android.png"
  flavors:
    main:
      image_path: "assets/icons/ios.png"
      adaptive_icon_background: "#0a0011"
      adaptive_icon_foreground: "assets/icons/android.png"
    dev:
      image_path: "assets/icons/ios.png"
      adaptive_icon_background: "#0a0011"
      adaptive_icon_foreground: "assets/icons/android.png"

flutter_native_splash:
  color: "#0a0011"
  image: assets/icons/about.png
  ios: true
  android: true
  android_12:
    image: assets/icons/about.png
    icon_background_color: "#0a0011"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ios.png"
  adaptive_icon_background: "#0a0011"
  adaptive_icon_foreground: "assets/icons/android.png"
  macos:
    generate: true
    image_path: assets/icons/ios.png
  flavors:
    main:
      image_path: "assets/icons/ios.png"
      adaptive_icon_background: "#0a0011"
      adaptive_icon_foreground: "assets/icons/android.png"
    dev:
      image_path: "assets/icons/ios.png"
      adaptive_icon_background: "#0a0011"
      adaptive_icon_foreground: "assets/icons/android.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/about.png

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic